config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users
  resources :teams
  resources :users, only: [:index, :show]
  resources :categories
  resources :resources do 
    post 'categorize/:category_id' => 'resources#categorize', as: :categorize
    post 'uncategorize/:category_id' => 'resources#uncategorize', as: :uncategorize
  end
  get 'visual' => 'visual#index'
  root 'categories#index'
end

app/views/resources/_card.html.erb
<section class="card resource">
  <%= link_to resource do %>
    <img class="card-img-top img-fluid" src="<%= resource.image %>">
    <div class="card-block">
      <h1 class="card-title"><%= resource.title %></h1>
      <p class="card-text"><%= resource.abstract %></p>
    </div>
    <div class="card-footer">
      <ul class="list-unstyled">
        <% unless resource.categories.empty? %>
          <li><%= fa_icon(:tags) %> <%= resource.categories.map { |c| link_to c.title, c }.join(', ').html_safe %></li>
        <% end %>
        <li><%= link_to "#{fa_icon(:link)} #{resource.url.truncate 30}".html_safe, resource.url, target: :blank %></li>
        <li><%= fa_icon(:calendar) %> <%= resource.created_at.strftime("%d/%m/%Y") %></li>
        <li><%= link_to "#{fa_icon(:user)} #{resource.user.to_s}".html_safe, resource.user %></li>
      </ul>
    </div>
  <% end %>
</section>

app/views/resources/_form.html.erb
<%= simple_form_for resource do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="col-md-8">
      <%= f.input :title %>
      <%= f.input :abstract %>
      <%= f.input :url %>
      <%= f.input :image %>
    </div>
    <div class="col-md-4">
      <%= link_to 'Cancel', resource, class: 'btn btn-primary' %>
      <%= f.submit 'Save', class: 'btn btn-primary' %>
      <h4>Categories</h4>
      <ul class="list-inline">
        <% Category.all.each do |category| %>
          <li class="list-inline-item">
            <% if category.in? resource.categories %>
              <%= link_to category.title, resource_uncategorize_path(resource, category), method: :post, class: 'btn btn-sm btn-info' %>
            <% else %>
              <%= link_to category.title, resource_categorize_path(resource, category), method: :post, class: 'btn btn-sm btn-secondary' %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/resources/_input.html.erb
<%= simple_form_for resource do |f| %>
  <%= f.association :categories, as: :hidden %>
  <div class="form-inline">
    <input type="text" class="form-control" name="resource[url]" id="resource_url" placeholder="Paste URL here">
    <button type="submit" class="btn btn-primary">Add resource</button>
  </div>
<% end %>

app/views/resources/edit.html.erb
<% content_for :title, @resource %>

<% content_for :jumbo do %>
  <h1>
    <%= @resource.title %>
  </h1>
<% end %>

<%= render 'form', resource: @resource %>

app/views/resources/index.html.erb
<div class="card-columns">
  <% @resources.each do |resource| %>
    <%= render 'card', resource: resource %>
  <% end %>
</div>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<% content_for :title, @resource %>

<% content_for :jumbo do %>
  <h1>
    <%= @resource.title %><br/>
    <%= link_to fa_icon(:pencil), edit_resource_path(@resource), class: 'mini-icon' %>
    <%= link_to fa_icon(:trash), @resource, method: :delete, data: { confirm: 'Are you sure?' }, class: 'mini-icon' %>
  </h1>
<% end %>

<div class="row">
  <div class="col-md-4">
    <p><%= @resource.abstract %></p>
  </div>
  <div class="col-md-4">
    <%= image_tag @resource.image, class: 'img-fluid' unless @resource.image.nil? %>
  </div>
  <div class="col-md-4">
    <ul class="list-unstyled">
      <li><%= link_to "#{fa_icon(:link)} #{@resource.url}".html_safe, @resource.url, target: :blank %></li>
      <li><%= fa_icon(:calendar) %> <%= @resource.created_at.strftime("%d/%m/%Y") %></li>
      <li><%= link_to "#{fa_icon(:user)} #{@resource.user.to_s}".html_safe, @resource.user %></li>
    </ul>
    <ul class="list-inline">
      <% @resource.categories.each do |category| %>
        <%= link_to category, category, class: 'btn btn-sm btn-info' %>
      <% end %>
    </ul>
  </div>
</div>