config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users
  resources :teams
  resources :users, only: [:index, :show]
  resources :categories
  resources :resources do 
    post 'categorize/:category_id' => 'resources#categorize', as: :categorize
    post 'uncategorize/:category_id' => 'resources#uncategorize', as: :uncategorize
  end
  get 'visual' => 'visual#index'
  root 'categories#index'
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
  has_and_belongs_to_many :resources

  def to_s
    "#{title}"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
    @resource = Resource.new
  end

  def show
    @resource = Resource.new
    @resource.categories << @category
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new category_params
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for category do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="col-md-8">
      <%= f.input :title %>
    </div>
    <div class="col-md-4">
      <%= link_to 'Cancel', category, class: 'btn btn-primary' %>
      <%= f.submit 'Save', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, @category %>

<% content_for :jumbo do %>
  <h1>
    <%= @category.title %>
  </h1>
<% end %>

<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<% content_for :jumbo do %>
  <h1>Categories</h1>
  <%= render 'resources/input', resource: @resource %>
<% end %>
<div class="card-columns">
  <% @categories.each do |category| %>
    <section class="card category">
      <div class="card-block">
        <span class="label label-pill label-default pull-right"><%= category.resources.count %></span>
        <h1 class="card-title">
          <%= link_to category.title, category %> 
        </h1> 
        <ul class="list-unstyled">
          <% category.resources.recent.each do |resource| %>
              <li class="card-text"><%= link_to resource, resource %></li>
          <% end %>
        </ul>
      </div>
    </section>
  <% end %>
  <section class="card new">
    <div class="card-block">
      <h1 class="card-title">
        <%= link_to 'Create new Category', new_category_path %>
      </h1> 
    </div>
  </section>
</div>

<%= link_to 'Live visual board', visual_path, class: 'btn btn-primary btn-sm' %>

app/views/categories/new.html.erb
<% content_for :title, 'New Category' %>

<% content_for :jumbo do %>
  <h1>New Category</h1>
<% end %>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<% content_for :title, @category %>
<% content_for :jumbo do %>
  <h1>
    <%= @category.title %><br/>
    <%= link_to fa_icon(:pencil), edit_category_path(@category), class: 'mini-icon' %>
    <%= link_to fa_icon(:trash), @category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'mini-icon' %>
  </h1>
  <%= render 'resources/input', resource: @resource %>
<% end %>
<header class="text-xs-center">
</header>
<div class="card-columns">
  <% @category.resources.ordered.each do |resource| %>
    <%= render 'resources/card', resource: resource %>
  <% end %>
</div>