config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users
  resources :teams
  resources :users, only: [:index, :show]
  resources :categories
  resources :resources do 
    post 'categorize/:category_id' => 'resources#categorize', as: :categorize
    post 'uncategorize/:category_id' => 'resources#uncategorize', as: :uncategorize
  end
  get 'visual' => 'visual#index'
  root 'categories#index'
end

app/controllers/visual_controller.rb
class VisualController < ApplicationController
  def index
    @resources = Resource.all.order(created_at: :desc).limit(20)
  end
end

app/views/visual/index.html.erb
<script>
function drawResources() {
  $('.main-card').html('');
  $('.card-columns').html('');
  for (var i in resources) {
    var resource = resources[i];
    html =  '<section class="card resource">';
    html += ' <a href="' + resource.path + '">';
    html += '   <img class="card-img-top img-fluid" src="' + resource.image + '">';
    html += '   <div class="card-block">'
    html += '     <h1 class="card-title">' + resource.title + '</h1>';
    html += '     <p class="card-text">' + resource.abstract + '</p>';
    html += '   </div>'
    html += ' </a>'
    html += '</section>'
    var target = i == 0 ? $('.main-card') : $('.card-columns');
    target.append(html);
  }  
}
var resources = [];
<% @resources.each do |resource| %>
  resources.push({
     "title": "<%= resource.title %>",
     "abstract": "<%= escape_javascript resource.abstract %>",
     "image": "<%= resource.image %>",
     "path": "<%= resource_path(resource) %>"
  });
<% end %>
$(function() {
  drawResources();
});
</script>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-4 main-card"></div>
    <div class="card-columns"></div>
  </div>
</div>